name: CI/CD Render

on:
    push:
        branches: ['main']

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm run test:cov

    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build

            - name: Upload dist artifact
              uses: actions/upload-artifact@v4
              with:
                  name: dist
                  path: dist/

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Download dist artifact
              uses: actions/download-artifact@v4
              with:
                  name: dist
                  path: dist/

            - name: Install Render CLI
              run: |
                  curl -sSL https://github.com/render-oss/cli/releases/download/v1.1.0/cli_1.1.0_linux_amd64.tar.gz -o render.tar.gz
                  tar -xzf render.tar.gz
                  sudo mv render /usr/local/bin/

            - name: Trigger Render Deploy
              env:
                  RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
              run: render deploys create ${{ secrets.RENDER_SERVICE_ID }} --confirm --wait
